server:
    port: 8536
    error:
        whitelabel:
            enabled: false
spring:
    datasource:
        url: jdbc:postgresql://192.168.56.100:5432/ggl_zone
        username: prt_ggl
        # 纯数字密码不会被正确识别，需要加上‘’
        password: '010427'
        driver-class-name: org.postgresql.Driver
    task:
        execution:
            pool:
                max-size: 6
                core-size: 3
                allow-core-thread-timeout: true
    thymeleaf:
        prefix: classpath:/static/
        suffix: .html    